DROP USER IF EXISTS anonymous@'%';
DROP USER IF EXISTS anonymous@'localhost';
DROP USER IF EXISTS admin@'%';
DROP USER IF EXISTS admin@'localhost';
-- GRANT USAGE ON *.* TO anonymous@'%' IDENTIFIED BY '';
-- DROP USER anonymous@'%';
-- GRANT USAGE ON *.* TO anonymous@localhost IDENTIFIED BY '';
-- DROP USER anonymous@localhost;
-- GRANT USAGE ON *.* TO admin@'%' IDENTIFIED BY '';
-- DROP USER admin@'%';
-- GRANT USAGE ON *.* TO admin@localhost IDENTIFIED BY '';
-- DROP USER admin@'localhost';
DROP VIEW IF EXISTS users_view;
DROP PROCEDURE IF EXISTS setup_role;
DROP PROCEDURE IF EXISTS remove_role;
DROP PROCEDURE IF EXISTS setup_tables_priv;
DROP PROCEDURE IF EXISTS setup_procs_priv;
DROP PROCEDURE IF EXISTS add_user_core;
DROP PROCEDURE IF EXISTS add_user;
DROP PROCEDURE IF EXISTS remove_user;
DROP PROCEDURE IF EXISTS remove_me;
DROP PROCEDURE IF EXISTS add_admin;
DROP PROCEDURE IF EXISTS remove_admin;
DROP PROCEDURE IF EXISTS update_me;
DROP PROCEDURE IF EXISTS update_user_core;
DROP PROCEDURE IF EXISTS update_user;
DROP PROCEDURE IF EXISTS update_password;
DROP PROCEDURE IF EXISTS add_friend;
DROP PROCEDURE IF EXISTS remove_friend;
DROP PROCEDURE IF EXISTS my_info;
DROP FUNCTION IF EXISTS safe_profile;
DROP FUNCTION IF EXISTS my_login_name;
DROP FUNCTION IF EXISTS my_role;
DROP FUNCTION IF EXISTS user_id;
DROP TABLE IF EXISTS auth_map;
DROP TABLE IF EXISTS lock_ctl;
DROP TABLE IF EXISTS users_friend_users;
DROP TABLE IF EXISTS users;
